spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

#    #默认一下security的用户名密码
  #  security:
  #    user:
  #      name: nip
  #      password: nip
##redis配置
#redis:
  # 地址
  host: 192.168.30.2
  # 端口，默认为6379
  port: 6379
  # 数据库索引
  database: 15
  # 密码
  password: 123
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms